Update 3-redirection

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,17 +1,32 @@
 #!/usr/bin/env bash
-apt-get update
-apt-get install -y nginx
+# Install and setup new nginx server
 
-mkdir /etc/nginx/html
-touch /etc/nginx/html/index.html
-echo "Hello World!" > /etc/nginx/html/index.html
-printf %s "server {
-    listen 80;
-    listen [::]:80 default_server;
-    root   /etc/nginx/html;
-    index  index.html index.htm;
-    location /redirect_me {
-        return 301 https://www.youtube.com/watch?v=BJLE8GGmY-I&t=323s/;
+apt-get update -y && \
+apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    service nginx start
+    echo -e \
+"http {
+    root /var/www/holberton;
+    server {
+        listen 80;
+        server_name pearmountain.space;
+        rewrite ^/redirect_me/? \
+https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
+        location / {
+            index index.html;
+        }
     }
-}" > /etc/nginx/sites-available/default
-service nginx restart
+}
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/holberton
+    echo "Holberton School" > \
+	/var/www/holberton/index.html
+    service nginx restart
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
